from turtle import *
class square(Turtle):
	def __init__(self,size):
		Turtle.__init__(self)
		self.shape('square')
		self.shapesize(size)
class hexagon(Turtle):
	def __init__(self,size):
		Turtle.__init__(self)
		self.begin_poly()
		self.fd(100)
		self.left(60)
		self.fd(100)
		self.left(60)
		self.fd(100)
		self.left(60)
		self.fd(100)
		self.left(60)
		self.fd(100)
		self.left(60)
		self.fd(100)
		self.left(60)
		self.fd(100)
		self.end_poly()
		p = self.get_poly()
		register_shape("hexagon", p)
		self.shape('hexagon')
		self.fd(100)
		self.left(60)
		self.fd(100)
		self.left(60)
		self.fd(100)
		self.left(60)
		self.fd(100)
		self.left(60)
		self.fd(100)
		self.left(60)
		self.fd(100)
		self.left(60)
		self.fd(100)
		

hx = hexagon(5)
